### ISSUE TITLE
Third Party Image Hosting

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#1143]
### Description

We have a growing issue with slowing builds, and a growing GH repo due to the number of images hosted here (mostly in blog articles).

We should consider switching our image hosting to something like S3, ideally with a pipeline that automatically does the same/relevant image compression as were implemented by @Pezmc for this repository.

In doing so, we can upload an article, have images stored in S3 (for example), and then this means our build process (which re-compresses all 600+ images each time we run) only ever needs to run for _new_ images, all past images will already have been processed and stored in the third-party storage.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Pezmc** [comment]
FWIW the build will only recompress an image if it has changed, but that assumes the cache is kept between builds. 

On Github Actions right now we're building from scratch each time, the [native cache action](https://github.com/actions/cache) could also speed up builds.

That being said, I support moving to S3 if the objective is faster loading of images since with a dedicated CDN it'll usually be faster.

**Comment by knolleary** [comment]
I'm not clear what the workflow would then be to get the images into S3 and what it means for a local clone of the website and images...

An alternative approach I'd like to propose:

1. Get rid of the image build process from the main build - have it just generate the site with image files as-is.
2. Have a GH action that runs on PRs - looks for any images touched by the PR, compresses them and adds a commit back to the PR with the compressed versions.

This will mean the files in `main` *should* be compressed and require no further effort and everything else Just Works.

This feels like far fewer moving parts and gets the build sped up.

**Comment by Pezmc** [comment]
Yes, the image pipeline is much more than compression @knolleary, as per above, we already have calibre do some basic lossless compression as a GitHub action.

The pipeline itself was about improving the google lighthouse score, so it is doing things including, but not limited to:

 - Inlining images below a certain size
 - Converting to modern file formats e.g. AVIF, WebP
 - Generating multiple sizes of each image to serve depending on user screen DPI
 - Downsizing images to the physical size they'll be displayed on screen.

I suppose _theoretically_ that could all be written to disk and committed to the repo, but it's not a small ask!

**Comment by knolleary** [comment]
Fair enough - was just looking for a quick win because the current situation doesn't feel very sustainable.

**Comment by knolleary** [comment]
The build is only slow in GH Actions due to the lack of caching. When netlify runs `npm run build` it takes a small fraction of the time - presumably they are caching the output.

The main DX issue we have is that it takes 30 minutes for the `Test` workflow to complete for each PR.

Have we ever had a test failure due to the images breaking links? How about we modify the Test workflow to run a build *without* the image pipeline - so we get the link checker results *much* quicker.

**Comment by Pezmc** [comment]
Yes, I proposed adding caching above.

Perhaps we split the image link checking into a separate action (without pipeline enabled) and also enable caching on the main build?

**Comment by knolleary** [comment]
I have raised #1194 which should add caching to the build/test action and greatly improve its run time.

**Comment by ZJvandeWeg** [comment]
With #1194 merged I'll close this as it's not a huge issue _at the moment_.
