### ISSUE TITLE
Create PDF version of STFI case study

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1425]
### Description

Create a PDF document of the case study so that it can be available to download via a form 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
Hi @Hasmin-AC [here it is](https://drive.google.com/open?id=1SUIj3PiAYatNioTPPuZ76h541uPZ3-HB&usp=drive_fs). I'm gonna use the same layout for the other ones, and add this as a template in the FlowFuse Google template gallery.

**Comment by Yndira-FlowForge** [comment]
This is the one I added as a template, and as requested, I just modified a copy of file to be two columns instead of one. Please, check it out before I update the template, it's [here](https://docs.google.com/document/d/1vhVX231PMEVI7qC2EJ6nyHeKwvdIelEuQfbCfCqqYxc/edit?usp=sharing). Let me know your thoughts.

**Comment by Hasmin-AC** [comment]
yes the two columns makes it much easier to read. thanks!
