### ISSUE TITLE
Pricing page iteration

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#1959]
### Description

- [x] Remove monthly/annually toggle
- [x] Add a third option to the self-hosted/cloud toggle: dedicated. https://github.com/FlowFuse/website/issues/1814
- [x] Unify CTAs in the hero section and below the features list. It would be:
    - try for free (cloud only) or install now (self-hosted)
    - book a demo
    -  request a quote (it has shown a better performance than contact us)
- [x] Remove the contact us form
- [x] Add a section for the trial enterprise license in self hosted
- [x] Add a FAQs section
- [x] Add social proof
- [x] Update the table and show features grouped by values according to [this sheet](https://docs.google.com/spreadsheets/d/1TTFwFjREKT6ngTbTVplsbALZajpy3h0UR8P8Jdos0pM/edit?usp=sharing)
- [x] Remove the subscription and support section
- [x] Committed SLA in the hero section

### Epic/Story

#1932

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @zackwasli, could you please share with me the FAQs to add them to the pricing page?

**Comment by zackwasli** [comment]
- Does FlowFuse offer annual discounts?
-Yes, we offer a 15% discount for annual subscriptions.

-Is there a minimum for purchase?
-Yes, 5 instances on Team and 10 instances on Enterprise.

-Why isn't there an option for self-hosted Team?
-Due to the configuration and support required for a self-hosted deployment, it is only possible through the Enterprise tier at this time.

**Comment by Yndira-E** [comment]
Thanks @zackwasli!
