### ISSUE TITLE
Update feature videos on website

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2249]
### Description

Update videos found on the [features page](https://flowfuse.com/product/features/) with new visuals and/or narrative. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@Hasmin-AC I thought I'd record the scripts only? Are the scripts available?

**Comment by Hasmin-AC** [comment]
Its mainly the visuals that need to be updated as they say FlowForge in the Screen grabs. 

I'll let @Yndira-E comment on which ones need new scripts too.

**Comment by Yndira-E** [comment]
There are 3 videos on that page:
1. [Centralized Instance Management](https://www.youtube.com/watch?v=KOnQnR7yfT0)
2. [Simplified Hosting and Maintenance](https://www.youtube.com/watch?v=Ec4yvcvGmu8)
3. [Software Delivery Pipelines and Version History](https://www.youtube.com/watch?v=Pbql22f3vqY)

The script for the second video is [here](https://docs.google.com/document/d/1oKT4O-eMF3SID-DePy_uAU3RYzRRb2LzecEF4sUTFuc/edit?usp=sharing).

The first two videos have the "reasons" format intro because they were initially intended for the "Why FlowFuse" page. Now that they're on the features page, we could consider removing that intro from both the script and the visuals.

Personally, I find it easier to create visuals and voice-over from scratch rather than matching visuals to a pre-recorded voice-over.

I can use Adobe Premiere to transcribe the audio from the other two videos and share it in a Google Doc. It won't be perfect, but perhaps @Hasmin-AC could then polish and improve the scripts as needed. Let me know if that works for everyone.
