### ISSUE TITLE
Self-hosted Enterprise tier pricing to "Let's talk"

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/website#2274]
### Description

The pricing for self-hosted Enterprise tier should be hidden again from prospects. This allows us to better understand what they're looking for and how we can serve them before discussing pricing.

I also think the CTA needs to be updated right below it, to ensure more people talk to us.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
@ZJvandeWeg this is a comparison before and after this change was introduced:

<img width="1272" alt="Screenshot 2024-07-16 at 20 00 51" src="https://github.com/user-attachments/assets/c906164d-96a5-47f5-bb60-8cb6d1b0602f">

It's performing better since we removed the slider and changed the CTA.

It's in this [dashboard](https://eu.posthog.com/project/2209/dashboard/58517) in case you'd like to check it.
