### ISSUE TITLE
Change our product menu on main nav and create landing pages accordingly

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#2275]
### Description

Change our current product menu to be something like:

Product:
- “ecosystem” TBD
  - FlowFuse
  - Device Agent
  - Dashboard
  - Project Nodes

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
@joepavitt This description is very simple. Do you think it accurately describes what you intended to convey during our call?

Feel free to add your reasoning behind this proposal or anything else you see fit.

While creating this, a question came up: where would the "FlowFuse" option take users? The [FlowFuse cloud landing page](https://flowfuse.com/product/cloud/) we recently created? Should we add two items instead: one for cloud and another for self-hosted?

**Comment by joepavitt** [comment]
I think the "FlowFuse" option would be the "Features" page - maybe? Or we list "Dashboard", "Agent", "Project Nodes" as a subsection of that navigation instead?

**Comment by Yndira-E** [comment]
Like this?

Product:
- Features
  - Dashboard
  - Device Agent
  - Project Nodes

**Comment by joepavitt** [comment]
Was more thinking:

- Features
- Customer Stories
- Blueprints
- FlowFuse Offerings:
    - FlowFuse Cloud
    - Dashboard
    - Device Agent
    - Project Nodes

**Comment by Yndira-E** [comment]
Ok, and isn't it FlowFuse self-hosted part of our offering?

For device Agent and Project nodes we don't have landing pages, but could link to docs lik in this PR: https://github.com/FlowFuse/website/pull/2302 WDYT?

**Comment by joepavitt** [comment]
The Device Agent page is being created at the moment in https://github.com/FlowFuse/website/issues/2236

For Project Nodes - docs is fine. Even docs for Device Agent (until the marketing page is ready) is also reasonable.

> FlowFuse self-hosted part of our offering?

Yes, that generally falls under the "Features" page really as it's common across all of FlowFuse (Cloud & Self-Hosted). The "Cloud" offering gets a particular call out because it's easier to sign up, etc.

I'd be open to having a "FlowFuse Self-Hosted" there too, maybe even changing it to:

- FlowFuse
    - Features
    - FlowFuse Cloud
- Customer Stories
- Blueprints
- Extras:
    - Dashboard
    - Device Agent
    - Project Nodes
