### ISSUE TITLE
OG Image for the roadmap page

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/website#596]
### Description

**Considerations:**
- Online social platforms

**Inspirations:**
- Other open graph images

There's multiple OG images already too

**Comment by joepavitt** [comment]
Quick lo-fi layout proposal:

<img width="708" alt="Screenshot 2023-04-11 at 18 28 32" src="https://user-images.githubusercontent.com/99246719/231242298-e3622742-2123-45e1-abea-4bd6214fe176.png">

file uploaded to https://drive.google.com/open?id=1-9-2GROWVJI4luUmsklfXHpeq0Yn_kxA&authuser=joepavitt%40flowforge.com&usp=drive_fs

**Comment by Yndira-FlowForge** [comment]
Thanks for the lo-fi @joepavitt 

I didn't do the roadmap cards exactly as they are on the web because I'm aware we'll improve those, so I thought each stage should have its own color and kept the emojis and descriptive text.

I noticed that currently, the upvote option is only available on the "under consideration" stage, I'm not sure if you have a reason behind it, but I think it would be better if they can upvote or like at any stage, it's still good feedback.

I also did the features list as grey rectangles, I thought if I added the current ones it would become obsolete really soon.

About the like icon being actioned I tried your suggestion, here it is
![og-product-roadmap-1](https://user-images.githubusercontent.com/129537638/231432304-bd01f39b-8369-4bb0-988a-a502537ad214.jpg)

I also tried adding transparency to the "unclicked" icons and making the clicked one with no transparency, bigger and tilted (as I imagine the interaction being like), but I'm not sure if it's as obvious as the one above...
![og-product-roadmap-2](https://user-images.githubusercontent.com/129537638/231433149-e74f30fe-a592-4fd6-912f-426e2d1e09a7.jpg)

And added the like emoji to the subtitle as well, trying to make a visual link between the "upvote" text and the image...

Let me know what you think :)

**Comment by joepavitt** [comment]
@Yndira-FlowForge this is absolutely spot on 👌

**Comment by joepavitt** [comment]
will also cc @MarianRaphael for feedback as this page is his baby

**Comment by MarianRaphael** [comment]
This looks absolutely fantastic! Great job
