### ISSUE TITLE
Images not loading in /docs

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#92]
### Current Behavior

https://flowforge.com/docs/admin/

Images are not loading correctly from within the `/docs` path of the website. These are loaded from the [flowforge/docs](https://github.com/flowforge/flowforge/tree/main/docs) repo. 

The image paths likely need to be re-written in order to load from the correct base path. This was recently achieved for the handbook with this line:

https://github.com/flowforge/website/blob/5bd975c85a7c4d5054aae1c54adef48fa1bb839c/.eleventy.js#L70

### Expected Behavior

Images should load, and not need to be manually re-written in the `/docs` source.

**Comment by PLCMercenary** [comment]
@joepavitt, I was trying to follow your advice and I located the `str.replace` for the handbook as an `eleventyConfig.addFilter`.  I tried to replicate this with another block to replace Doc links with no success. 

I found that the replaceHandbookLinks filter is called in the `src/_includes/layouts/Handbook.njk` with a template that pipes content to the regex and then to safe. I am not sure what that template is doing.  Digging into the other .nlk files, I tried using the template on the bottom of pages.njk to pipe content to replace handbook links and that appears to never finish building and just passes ALL the content to to that filter (which in retrospect makes sense) 

After adding a few lines to the eleventy.js config to `    eleventyConfig.addPassthroughCopy("src/docs/admin/images"); `
also for docs/install and docs/contribute. The images are working in docs locally. 

So I assume that the regex you recommended in the 11ty filter, should be moving the images from each of the docs's sections, into the src/images directory. so that the docs can be edited and images added locally with a changed section MD then moved to src/images for publishing?

**Comment by joepavitt** [comment]
Great work on finding the `addPassthroughCopy`. Is it worth having something like `"src/**/images"` to prevent us needing to add exceptions for all new folders if we get new pages, etc.

Not sure I've put the correct syntax there, but that should be about right?

**Comment by joepavitt** [comment]
@PLCMercenary can you open a PR for this please, and we can get it merged
